<?php

namespace Tests\Feature;

use Illuminate\Support\Facades\Route;
use Tests\TestCase;

/**
 * Phase 2 moved no routes, renamed nothing and changed no middleware. This
 * freezes the name -> uri -> middleware map so a future route edit has to be a
 * deliberate, visible change rather than an accidental one.
 *
 * Regenerate the fixture with:
 *   php artisan route:list --json | php -r '...'
 * after an INTENDED route change, and record the reason in the commit message.
 */
class RouteParityTest extends TestCase
{
    public function test_the_route_map_matches_the_recorded_baseline(): void
    {
        $baseline = $this->baseline();
        $current = $this->currentRouteMap();

        $missing = array_values(array_diff($baseline, $current));
        $added = array_values(array_diff($current, $baseline));

        $this->assertSame([], $missing, 'Routes present in the baseline are missing or changed.');
        $this->assertSame([], $added, 'Routes were added or changed without updating the baseline.');
    }

    public function test_no_route_is_defined_twice_for_the_same_method_and_uri(): void
    {
        $seen = [];
        $duplicates = [];

        foreach ($this->currentRouteMap() as $entry) {
            [$method, $uri] = explode('|', $entry, 3);

            $key = $method.'|'.$uri;

            if (isset($seen[$key])) {
                $duplicates[] = $key;
            }

            $seen[$key] = true;
        }

        $this->assertSame([], $duplicates, 'A method/uri pair is registered more than once.');
    }

    /**
     * The To-Do surface, pinned route by route so a later accidental addition is
     * visible. The parity fixture is regenerated by hand, so without this the
     * module could quietly grow a route nobody reviewed.
     *
     * Phase 5 declared the CRUD/lifecycle set; Phase 7 added the cross-module
     * link endpoints and the cross-module "My Work" feed.
     */
    /**
     * Phase 8 added six Task routes. Pinned for the same reason as the To-Do set:
     * the parity fixture is regenerated by hand, so an accidental addition would
     * otherwise be invisible.
     */
    public function test_the_phase_eight_task_routes_are_exactly_what_was_declared(): void
    {
        $expected = [
            'tasks.subtasks.store',
            'tasks.parent.update',
            'tasks.watchers.store',
            'tasks.watchers.destroy',
            'tasks.time-entries.store',
            'tasks.time-entries.destroy',
            'tasks.tags.store',
            'tasks.tags.destroy',
        ];

        $actual = [];

        foreach (Route::getRoutes() as $route) {
            $name = (string) $route->getName();

            if (in_array($name, $expected, true)) {
                $actual[] = $name;
            }
        }

        sort($expected);
        sort($actual);

        $this->assertSame($expected, $actual);
    }

    public function test_the_todo_surface_is_exactly_what_was_declared(): void
    {
        $expected = [
            'todos.index', 'todos.inbox', 'todos.calendar', 'todos.create', 'todos.store',
            'todos.show', 'todos.edit', 'todos.update', 'todos.destroy', 'todos.bulk',
            'todos.complete', 'todos.reopen', 'todos.archive', 'todos.restore', 'todos.assign',
            'todos.status', 'todos.reports', 'todos.reports.export',
            'todos.notification-logs.index', 'todos.notification-logs.destroy',
            'todos.checklist.store', 'todos.checklist.update', 'todos.checklist.destroy',
            'todos.comments.store',
            'todos.watchers.store', 'todos.watchers.destroy',
            'todos.links.store', 'todos.links.destroy',
            // Phase 7: one-click To-Do creation from another module, and the
            // reverse navigation that answers "which To-Dos point at this record".
            'todos.links.from.action-item', 'todos.links.from.obligation',
            'todos.links.from.task', 'todos.links.reverse',
        ];

        $actual = [];

        foreach (Route::getRoutes() as $route) {
            if (str_starts_with((string) $route->getName(), 'todos.')) {
                $actual[] = $route->getName();
            }
        }

        sort($expected);
        sort($actual);

        $this->assertSame($expected, $actual);
    }

    /**
     * The To-Do routes, and the cross-module feed, are `web` + `auth` and nothing
     * else. A To-Do id in a URL must not be reachable without a session.
     */
    public function test_every_todo_route_requires_authentication(): void
    {
        foreach (Route::getRoutes() as $route) {
            $name = (string) $route->getName();

            if (! str_starts_with($name, 'todos.') && $name !== 'my-work') {
                continue;
            }

            $this->assertContains(
                'auth',
                $route->gatherMiddleware(),
                "{$name} is not behind the auth middleware.",
            );
        }
    }

    /**
     * `my-work` spans four modules, so it must not live under the `todos.` prefix
     * where a To-Do action would be a more natural expectation.
     */
    public function test_the_cross_module_feed_is_not_nested_under_todos(): void
    {
        $route = collect(Route::getRoutes())->first(
            fn ($candidate): bool => $candidate->getName() === 'my-work',
        );

        $this->assertNotNull($route);
        $this->assertSame('my-work', $route->uri());
        $this->assertSame('GET', $route->methods()[0]);
    }

    public function test_every_named_route_still_resolves_to_a_url(): void
    {
        $unnamed = [];

        foreach (Route::getRoutes() as $route) {
            if ($route->getName() === null) {
                continue;
            }

            // A named route with no parameters must still generate a URL.
            if ($route->parameterNames() === [] && ! str_contains($route->uri(), '{')) {
                try {
                    route($route->getName());
                } catch (\Throwable $e) {
                    $unnamed[] = $route->getName().': '.$e->getMessage();
                }
            }
        }

        $this->assertSame([], $unnamed);
    }

    /**
     * @return list<string>
     */
    private function baseline(): array
    {
        $path = __DIR__.'/../Fixtures/routes-baseline.json';

        $this->assertFileExists($path, 'The route baseline fixture is missing.');

        $contents = json_decode((string) file_get_contents($path), true);

        $this->assertIsArray($contents, 'The route baseline fixture is not valid JSON.');

        return $contents;
    }

    /**
     * @return list<string>
     */
    private function currentRouteMap(): array
    {
        $entries = [];

        foreach (Route::getRoutes() as $route) {
            // Boost registers its own tooling routes, and only outside the testing
            // environment. They are not application routes, so they are excluded
            // from both sides of the comparison.
            if (str_starts_with((string) $route->getName(), 'boost.')) {
                continue;
            }

            $entries[] = implode('|', [
                $route->methods()[0] ?? '',
                $route->uri(),
                $route->getName() ?? '',
                $this->middlewareSignature($route->gatherMiddleware()),
            ]);
        }

        sort($entries);

        return $entries;
    }

    /**
     * `gatherMiddleware()` returns class names with escaped namespace separators,
     * which is not the form recorded in the fixture.
     *
     * @param  array<int, string>  $middleware
     */
    private function middlewareSignature(array $middleware): string
    {
        $normalised = array_map(
            fn (string $name): string => str_replace('\\\\', '\\', ltrim($name, '\\')),
            $middleware,
        );

        sort($normalised);

        return implode(',', $normalised);
    }
}
